### ISSUE TITLE
Can't compile ;)

### ISSUE THREAD

**Issue by rinogo** [jitsi/jitsi-meet-ios#1]
No matter what I do, I can't get this to work! :)

The Jitsi FAQ mentions that it's unlikely that an iOS app will ever exist https://jitsi.org/Documentation/FAQ#toc24 - Can you shed any light on why that might be?  Possibly for the same reasons this project hasn't seen more commits?

Thank you so much!

**Comment by jeffclay** [comment]
@rinogo I've found that the documentation is very lacking. Also, there is an iOS and an Android app for Jitsi Meet. I haven't tested it, but I believe the code for the iOS aspect is here https://github.com/jitsi/jitsi-meet/tree/master/ios

**Comment by rinogo** [comment]
Thanks, @jeffclay!

**Comment by lyubomir** [comment]
The FAQ is talking about the Jitsi desktop client. This repository is called jitsi-meet-ios so that the FAQ may not apply. Anyway, this repository exists for history purposes only. We have Android and iOS apps for Jitsi Meet (that's software completely different from Jitsi desktop) and they live where Jitsi Meet for Web lives i.e. in jitsi-meet. The Android and iOS apps are written with React Native so they run parts of the source code that the Web app runs. For iOS, you'll find some minimal source code in ios/ but then you'll also want to look at react/ for most of the logic of the app. Building jitsi-meet for iOS is a different subject (even though it's not documented at this point).
